name: Build Dist

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run the build and commit action'
        required: true

jobs:
  build:
    name: Build and commit
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build with webpack
        run: npm run build

      - name: Commit dist file
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Build"
            git push